import type { Ats } from "@/lib/ats/types";

export type SeedCompany = {
  slug: string;
  name: string;
  ats: Ats;
  boardToken: string;
  careersUrl: string;
  website: string;
};

/** Tokens confirmed against live public board APIs during implementation. */
export const SEED_COMPANIES: SeedCompany[] = [
  {
    slug: "stripe",
    name: "Stripe",
    ats: "greenhouse",
    boardToken: "stripe",
    careersUrl: "https://stripe.com/jobs",
    website: "https://stripe.com",
  },
  {
    slug: "anthropic",
    name: "Anthropic",
    ats: "greenhouse",
    boardToken: "anthropic",
    careersUrl: "https://job-boards.greenhouse.io/anthropic",
    website: "https://www.anthropic.com",
  },
  {
    slug: "airbnb",
    name: "Airbnb",
    ats: "greenhouse",
    boardToken: "airbnb",
    careersUrl: "https://careers.airbnb.com",
    website: "https://www.airbnb.com",
  },
  {
    slug: "coinbase",
    name: "Coinbase",
    ats: "greenhouse",
    boardToken: "coinbase",
    careersUrl: "https://www.coinbase.com/careers",
    website: "https://www.coinbase.com",
  },
  {
    slug: "discord",
    name: "Discord",
    ats: "greenhouse",
    boardToken: "discord",
    careersUrl: "https://discord.com/careers",
    website: "https://discord.com",
  },
  {
    slug: "figma",
    name: "Figma",
    ats: "greenhouse",
    boardToken: "figma",
    careersUrl: "https://www.figma.com/careers",
    website: "https://www.figma.com",
  },
  {
    slug: "cloudflare",
    name: "Cloudflare",
    ats: "greenhouse",
    boardToken: "cloudflare",
    careersUrl: "https://www.cloudflare.com/careers",
    website: "https://www.cloudflare.com",
  },
  {
    slug: "databricks",
    name: "Databricks",
    ats: "greenhouse",
    boardToken: "databricks",
    careersUrl: "https://www.databricks.com/company/careers",
    website: "https://www.databricks.com",
  },
  {
    slug: "vercel",
    name: "Vercel",
    ats: "greenhouse",
    boardToken: "vercel",
    careersUrl: "https://vercel.com/careers",
    website: "https://vercel.com",
  },
  {
    slug: "dropbox",
    name: "Dropbox",
    ats: "greenhouse",
    boardToken: "dropbox",
    careersUrl: "https://jobs.dropbox.com",
    website: "https://www.dropbox.com",
  },
  {
    slug: "robinhood",
    name: "Robinhood",
    ats: "greenhouse",
    boardToken: "robinhood",
    careersUrl: "https://careers.robinhood.com",
    website: "https://robinhood.com",
  },
  {
    slug: "block",
    name: "Block",
    ats: "greenhouse",
    boardToken: "block",
    careersUrl: "https://block.xyz/careers",
    website: "https://block.xyz",
  },
  {
    slug: "lyft",
    name: "Lyft",
    ats: "greenhouse",
    boardToken: "lyft",
    careersUrl: "https://www.lyft.com/careers",
    website: "https://www.lyft.com",
  },
  {
    slug: "openai",
    name: "OpenAI",
    ats: "ashby",
    boardToken: "openai",
    careersUrl: "https://jobs.ashbyhq.com/openai",
    website: "https://openai.com",
  },
  {
    slug: "ramp",
    name: "Ramp",
    ats: "ashby",
    boardToken: "ramp",
    careersUrl: "https://jobs.ashbyhq.com/ramp",
    website: "https://ramp.com",
  },
  {
    slug: "linear",
    name: "Linear",
    ats: "ashby",
    boardToken: "linear",
    careersUrl: "https://linear.app/careers",
    website: "https://linear.app",
  },
  {
    slug: "notion",
    name: "Notion",
    ats: "ashby",
    boardToken: "notion",
    careersUrl: "https://jobs.ashbyhq.com/notion",
    website: "https://www.notion.so",
  },
  {
    slug: "cursor",
    name: "Cursor",
    ats: "ashby",
    boardToken: "cursor",
    careersUrl: "https://jobs.ashbyhq.com/cursor",
    website: "https://cursor.com",
  },
  {
    slug: "palantir",
    name: "Palantir",
    ats: "lever",
    boardToken: "palantir",
    careersUrl: "https://jobs.lever.co/palantir",
    website: "https://www.palantir.com",
  },
  {
    slug: "wealthfront",
    name: "Wealthfront",
    ats: "lever",
    boardToken: "wealthfront",
    careersUrl: "https://jobs.lever.co/wealthfront",
    website: "https://www.wealthfront.com",
  },
  {
    slug: "pinterest",
    name: "Pinterest",
    ats: "greenhouse",
    boardToken: "pinterest",
    careersUrl: "https://www.pinterestcareers.com",
    website: "https://www.pinterest.com",
  },
  {
    slug: "reddit",
    name: "Reddit",
    ats: "greenhouse",
    boardToken: "reddit",
    careersUrl: "https://www.redditinc.com/careers",
    website: "https://www.reddit.com",
  },
  {
    slug: "twilio",
    name: "Twilio",
    ats: "greenhouse",
    boardToken: "twilio",
    careersUrl: "https://www.twilio.com/company/jobs",
    website: "https://www.twilio.com",
  },
  {
    slug: "datadog",
    name: "Datadog",
    ats: "greenhouse",
    boardToken: "datadog",
    careersUrl: "https://careers.datadoghq.com",
    website: "https://www.datadoghq.com",
  },
  {
    slug: "mongodb",
    name: "MongoDB",
    ats: "greenhouse",
    boardToken: "mongodb",
    careersUrl: "https://www.mongodb.com/careers",
    website: "https://www.mongodb.com",
  },
  {
    slug: "instacart",
    name: "Instacart",
    ats: "greenhouse",
    boardToken: "instacart",
    careersUrl: "https://instacart.careers",
    website: "https://www.instacart.com",
  },
  {
    slug: "roblox",
    name: "Roblox",
    ats: "greenhouse",
    boardToken: "roblox",
    careersUrl: "https://careers.roblox.com",
    website: "https://www.roblox.com",
  },
  {
    slug: "gitlab",
    name: "GitLab",
    ats: "greenhouse",
    boardToken: "gitlab",
    careersUrl: "https://about.gitlab.com/jobs",
    website: "https://gitlab.com",
  },
  {
    slug: "grafana",
    name: "Grafana Labs",
    ats: "greenhouse",
    boardToken: "grafanalabs",
    careersUrl: "https://grafana.com/about/careers",
    website: "https://grafana.com",
  },
  {
    slug: "asana",
    name: "Asana",
    ats: "greenhouse",
    boardToken: "asana",
    careersUrl: "https://asana.com/jobs",
    website: "https://asana.com",
  },
  {
    slug: "okta",
    name: "Okta",
    ats: "greenhouse",
    boardToken: "okta",
    careersUrl: "https://www.okta.com/company/careers",
    website: "https://www.okta.com",
  },
  {
    slug: "perplexity",
    name: "Perplexity",
    ats: "ashby",
    boardToken: "perplexity",
    careersUrl: "https://www.perplexity.ai/careers",
    website: "https://www.perplexity.ai",
  },
  {
    slug: "supabase",
    name: "Supabase",
    ats: "ashby",
    boardToken: "supabase",
    careersUrl: "https://supabase.com/careers",
    website: "https://supabase.com",
  },
  {
    slug: "spotify",
    name: "Spotify",
    ats: "lever",
    boardToken: "spotify",
    careersUrl: "https://www.lifeatspotify.com",
    website: "https://www.spotify.com",
  },
];

export const STARTER_SLUGS = [
  "stripe",
  "anthropic",
  "discord",
  "figma",
  "coinbase",
  "cloudflare",
] as const;
