/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as EmployersRouteImport } from './routes/employers'
import { Route as ClosedRouteImport } from './routes/closed'
import { Route as ExpiredRouteImport } from './routes/expired'
import { Route as PlacementsRouteImport } from './routes/placements'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ApiDeskRouteImport } from './routes/api/desk'
import { Route as ApiClosedRouteImport } from './routes/api/closed'
import { Route as ApiExpiredRouteImport } from './routes/api/expired'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiHomeRouteImport } from './routes/api/home'
import { Route as CompaniesIndexRouteImport } from './routes/companies.index'
import { Route as CompaniesSlugRouteImport } from './routes/companies.$slug'
import { Route as JobsIndexRouteImport } from './routes/jobs.index'
import { Route as JobsIdRouteImport } from './routes/jobs.$id'
import { Route as LegalPrivacyRouteImport } from './routes/legal.privacy'
import { Route as LegalSourcingRouteImport } from './routes/legal.sourcing'
import { Route as LegalTermsRouteImport } from './routes/legal.terms'
import { Route as ApiCompaniesIndexRouteImport } from './routes/api/companies.index'
import { Route as ApiCompaniesSlugRouteImport } from './routes/api/companies.$slug'
import { Route as ApiCronCrawlRouteImport } from './routes/api/cron/crawl'
import { Route as ApiJobsIndexRouteImport } from './routes/api/jobs.index'
import { Route as ApiJobsIdRouteImport } from './routes/api/jobs.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployersRoute = EmployersRouteImport.update({
  id: '/employers',
  path: '/employers',
  getParentRoute: () => rootRouteImport,
} as any)
const ClosedRoute = ClosedRouteImport.update({
  id: '/closed',
  path: '/closed',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpiredRoute = ExpiredRouteImport.update({
  id: '/expired',
  path: '/expired',
  getParentRoute: () => rootRouteImport,
} as any)
const PlacementsRoute = PlacementsRouteImport.update({
  id: '/placements',
  path: '/placements',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiClosedRoute = ApiClosedRouteImport.update({
  id: '/api/closed',
  path: '/api/closed',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiExpiredRoute = ApiExpiredRouteImport.update({
  id: '/api/expired',
  path: '/api/expired',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDeskRoute = ApiDeskRouteImport.update({
  id: '/api/desk',
  path: '/api/desk',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHomeRoute = ApiHomeRouteImport.update({
  id: '/api/home',
  path: '/api/home',
  getParentRoute: () => rootRouteImport,
} as any)
const CompaniesIndexRoute = CompaniesIndexRouteImport.update({
  id: '/companies/',
  path: '/companies/',
  getParentRoute: () => rootRouteImport,
} as any)
const CompaniesSlugRoute = CompaniesSlugRouteImport.update({
  id: '/companies/$slug',
  path: '/companies/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsIndexRoute = JobsIndexRouteImport.update({
  id: '/jobs/',
  path: '/jobs/',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsIdRoute = JobsIdRouteImport.update({
  id: '/jobs/$id',
  path: '/jobs/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalPrivacyRoute = LegalPrivacyRouteImport.update({
  id: '/legal/privacy',
  path: '/legal/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalSourcingRoute = LegalSourcingRouteImport.update({
  id: '/legal/sourcing',
  path: '/legal/sourcing',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalTermsRoute = LegalTermsRouteImport.update({
  id: '/legal/terms',
  path: '/legal/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCompaniesIndexRoute = ApiCompaniesIndexRouteImport.update({
  id: '/api/companies/',
  path: '/api/companies/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCompaniesSlugRoute = ApiCompaniesSlugRouteImport.update({
  id: '/api/companies/$slug',
  path: '/api/companies/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronCrawlRoute = ApiCronCrawlRouteImport.update({
  id: '/api/cron/crawl',
  path: '/api/cron/crawl',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiJobsIndexRoute = ApiJobsIndexRouteImport.update({
  id: '/api/jobs/',
  path: '/api/jobs/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiJobsIdRoute = ApiJobsIdRouteImport.update({
  id: '/api/jobs/$id',
  path: '/api/jobs/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/contact': typeof ContactRoute
  '/employers': typeof EmployersRoute
  '/closed': typeof ClosedRoute
  '/expired': typeof ExpiredRoute
  '/placements': typeof PlacementsRoute
  '/api/closed': typeof ApiClosedRoute
  '/api/expired': typeof ApiExpiredRoute
  '/pricing': typeof PricingRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/desk': typeof ApiDeskRoute
  '/api/health': typeof ApiHealthRoute
  '/api/home': typeof ApiHomeRoute
  '/companies/$slug': typeof CompaniesSlugRoute
  '/jobs/$id': typeof JobsIdRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/sourcing': typeof LegalSourcingRoute
  '/legal/terms': typeof LegalTermsRoute
  '/companies/': typeof CompaniesIndexRoute
  '/jobs/': typeof JobsIndexRoute
  '/api/companies/$slug': typeof ApiCompaniesSlugRoute
  '/api/cron/crawl': typeof ApiCronCrawlRoute
  '/api/jobs/$id': typeof ApiJobsIdRoute
  '/api/companies/': typeof ApiCompaniesIndexRoute
  '/api/jobs/': typeof ApiJobsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/contact': typeof ContactRoute
  '/employers': typeof EmployersRoute
  '/closed': typeof ClosedRoute
  '/expired': typeof ExpiredRoute
  '/placements': typeof PlacementsRoute
  '/api/closed': typeof ApiClosedRoute
  '/api/expired': typeof ApiExpiredRoute
  '/pricing': typeof PricingRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/desk': typeof ApiDeskRoute
  '/api/health': typeof ApiHealthRoute
  '/api/home': typeof ApiHomeRoute
  '/companies/$slug': typeof CompaniesSlugRoute
  '/jobs/$id': typeof JobsIdRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/sourcing': typeof LegalSourcingRoute
  '/legal/terms': typeof LegalTermsRoute
  '/companies': typeof CompaniesIndexRoute
  '/jobs': typeof JobsIndexRoute
  '/api/companies/$slug': typeof ApiCompaniesSlugRoute
  '/api/cron/crawl': typeof ApiCronCrawlRoute
  '/api/jobs/$id': typeof ApiJobsIdRoute
  '/api/companies': typeof ApiCompaniesIndexRoute
  '/api/jobs': typeof ApiJobsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/contact': typeof ContactRoute
  '/employers': typeof EmployersRoute
  '/closed': typeof ClosedRoute
  '/expired': typeof ExpiredRoute
  '/placements': typeof PlacementsRoute
  '/api/closed': typeof ApiClosedRoute
  '/api/expired': typeof ApiExpiredRoute
  '/pricing': typeof PricingRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/desk': typeof ApiDeskRoute
  '/api/health': typeof ApiHealthRoute
  '/api/home': typeof ApiHomeRoute
  '/companies/$slug': typeof CompaniesSlugRoute
  '/jobs/$id': typeof JobsIdRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/sourcing': typeof LegalSourcingRoute
  '/legal/terms': typeof LegalTermsRoute
  '/companies/': typeof CompaniesIndexRoute
  '/jobs/': typeof JobsIndexRoute
  '/api/companies/$slug': typeof ApiCompaniesSlugRoute
  '/api/cron/crawl': typeof ApiCronCrawlRoute
  '/api/jobs/$id': typeof ApiJobsIdRoute
  '/api/companies/': typeof ApiCompaniesIndexRoute
  '/api/jobs/': typeof ApiJobsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/contact'
    | '/employers'
    | '/closed'
    | '/expired'
    | '/placements'
    | '/api/closed'
    | '/api/expired'
    | '/pricing'
    | '/sitemap.xml'
    | '/api/desk'
    | '/api/health'
    | '/api/home'
    | '/companies/$slug'
    | '/jobs/$id'
    | '/legal/privacy'
    | '/legal/sourcing'
    | '/legal/terms'
    | '/companies/'
    | '/jobs/'
    | '/api/companies/$slug'
    | '/api/cron/crawl'
    | '/api/jobs/$id'
    | '/api/companies/'
    | '/api/jobs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/contact'
    | '/employers'
    | '/closed'
    | '/expired'
    | '/placements'
    | '/api/closed'
    | '/api/expired'
    | '/pricing'
    | '/sitemap.xml'
    | '/api/desk'
    | '/api/health'
    | '/api/home'
    | '/companies/$slug'
    | '/jobs/$id'
    | '/legal/privacy'
    | '/legal/sourcing'
    | '/legal/terms'
    | '/companies'
    | '/jobs'
    | '/api/companies/$slug'
    | '/api/cron/crawl'
    | '/api/jobs/$id'
    | '/api/companies'
    | '/api/jobs'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/contact'
    | '/employers'
    | '/closed'
    | '/expired'
    | '/placements'
    | '/api/closed'
    | '/api/expired'
    | '/pricing'
    | '/sitemap.xml'
    | '/api/desk'
    | '/api/health'
    | '/api/home'
    | '/companies/$slug'
    | '/jobs/$id'
    | '/legal/privacy'
    | '/legal/sourcing'
    | '/legal/terms'
    | '/companies/'
    | '/jobs/'
    | '/api/companies/$slug'
    | '/api/cron/crawl'
    | '/api/jobs/$id'
    | '/api/companies/'
    | '/api/jobs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  ContactRoute: typeof ContactRoute
  EmployersRoute: typeof EmployersRoute
  ClosedRoute: typeof ClosedRoute
  ExpiredRoute: typeof ExpiredRoute
  PlacementsRoute: typeof PlacementsRoute
  ApiClosedRoute: typeof ApiClosedRoute
  ApiExpiredRoute: typeof ApiExpiredRoute
  PricingRoute: typeof PricingRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiDeskRoute: typeof ApiDeskRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiHomeRoute: typeof ApiHomeRoute
  CompaniesSlugRoute: typeof CompaniesSlugRoute
  JobsIdRoute: typeof JobsIdRoute
  LegalPrivacyRoute: typeof LegalPrivacyRoute
  LegalSourcingRoute: typeof LegalSourcingRoute
  LegalTermsRoute: typeof LegalTermsRoute
  CompaniesIndexRoute: typeof CompaniesIndexRoute
  JobsIndexRoute: typeof JobsIndexRoute
  ApiCompaniesSlugRoute: typeof ApiCompaniesSlugRoute
  ApiCronCrawlRoute: typeof ApiCronCrawlRoute
  ApiJobsIdRoute: typeof ApiJobsIdRoute
  ApiCompaniesIndexRoute: typeof ApiCompaniesIndexRoute
  ApiJobsIndexRoute: typeof ApiJobsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employers': {
      id: '/employers'
      path: '/employers'
      fullPath: '/employers'
      preLoaderRoute: typeof EmployersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/closed': {
      id: '/closed'
      path: '/closed'
      fullPath: '/closed'
      preLoaderRoute: typeof ClosedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expired': {
      id: '/expired'
      path: '/expired'
      fullPath: '/expired'
      preLoaderRoute: typeof ExpiredRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/placements': {
      id: '/placements'
      path: '/placements'
      fullPath: '/placements'
      preLoaderRoute: typeof PlacementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/closed': {
      id: '/api/closed'
      path: '/api/closed'
      fullPath: '/api/closed'
      preLoaderRoute: typeof ApiClosedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/expired': {
      id: '/api/expired'
      path: '/api/expired'
      fullPath: '/api/expired'
      preLoaderRoute: typeof ApiExpiredRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/desk': {
      id: '/api/desk'
      path: '/api/desk'
      fullPath: '/api/desk'
      preLoaderRoute: typeof ApiDeskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/home': {
      id: '/api/home'
      path: '/api/home'
      fullPath: '/api/home'
      preLoaderRoute: typeof ApiHomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/companies/': {
      id: '/companies/'
      path: '/companies'
      fullPath: '/companies/'
      preLoaderRoute: typeof CompaniesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/companies/$slug': {
      id: '/companies/$slug'
      path: '/companies/$slug'
      fullPath: '/companies/$slug'
      preLoaderRoute: typeof CompaniesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/': {
      id: '/jobs/'
      path: '/jobs'
      fullPath: '/jobs/'
      preLoaderRoute: typeof JobsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/$id': {
      id: '/jobs/$id'
      path: '/jobs/$id'
      fullPath: '/jobs/$id'
      preLoaderRoute: typeof JobsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/privacy': {
      id: '/legal/privacy'
      path: '/legal/privacy'
      fullPath: '/legal/privacy'
      preLoaderRoute: typeof LegalPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/sourcing': {
      id: '/legal/sourcing'
      path: '/legal/sourcing'
      fullPath: '/legal/sourcing'
      preLoaderRoute: typeof LegalSourcingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/terms': {
      id: '/legal/terms'
      path: '/legal/terms'
      fullPath: '/legal/terms'
      preLoaderRoute: typeof LegalTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/companies/': {
      id: '/api/companies/'
      path: '/api/companies'
      fullPath: '/api/companies/'
      preLoaderRoute: typeof ApiCompaniesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/companies/$slug': {
      id: '/api/companies/$slug'
      path: '/api/companies/$slug'
      fullPath: '/api/companies/$slug'
      preLoaderRoute: typeof ApiCompaniesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/crawl': {
      id: '/api/cron/crawl'
      path: '/api/cron/crawl'
      fullPath: '/api/cron/crawl'
      preLoaderRoute: typeof ApiCronCrawlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/jobs/': {
      id: '/api/jobs/'
      path: '/api/jobs'
      fullPath: '/api/jobs/'
      preLoaderRoute: typeof ApiJobsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/jobs/$id': {
      id: '/api/jobs/$id'
      path: '/api/jobs/$id'
      fullPath: '/api/jobs/$id'
      preLoaderRoute: typeof ApiJobsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  ContactRoute: ContactRoute,
  EmployersRoute: EmployersRoute,
  ClosedRoute: ClosedRoute,
  ExpiredRoute: ExpiredRoute,
  PlacementsRoute: PlacementsRoute,
  ApiClosedRoute: ApiClosedRoute,
  ApiExpiredRoute: ApiExpiredRoute,
  PricingRoute: PricingRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiDeskRoute: ApiDeskRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiHomeRoute: ApiHomeRoute,
  CompaniesSlugRoute: CompaniesSlugRoute,
  JobsIdRoute: JobsIdRoute,
  LegalPrivacyRoute: LegalPrivacyRoute,
  LegalSourcingRoute: LegalSourcingRoute,
  LegalTermsRoute: LegalTermsRoute,
  CompaniesIndexRoute: CompaniesIndexRoute,
  JobsIndexRoute: JobsIndexRoute,
  ApiCompaniesSlugRoute: ApiCompaniesSlugRoute,
  ApiCronCrawlRoute: ApiCronCrawlRoute,
  ApiJobsIdRoute: ApiJobsIdRoute,
  ApiCompaniesIndexRoute: ApiCompaniesIndexRoute,
  ApiJobsIndexRoute: ApiJobsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
